version: '3.7'

services:
  redis:
    image: angelo87dock/gsweb-redis
    container_name: infra-redis
    restart: "always"
    volumes:
      - /docker/storage/storage-redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - lan-network

  rabbitmq:
    image: angelo87dock/gsweb-rabbitmq
    container_name: infra-rabbitmq
    restart: "always"
    environment:
      - RABBITMQ_DEFAULT_USER=CHANGE-ME
      - RABBITMQ_DEFAULT_PASS=CHANGE-ME
      - RABBITMQ_NODENAME=rabbit@localhost
    volumes:
      - /docker/storage/storage-rabbitmq/files:/var/lib/rabbitmq
      - /docker/storage/storage-rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - lan-network

  sqlserver:
    image: angelo87dock/gsweb-sqlserver
    container_name: infra-sqlserver
    user: root
    restart: "always"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CHANGE-ME
      - MSSQL_PID=Express
      - TZ=Europe/Rome
    volumes:
      - /docker/storage/storage-sqlserver/data:/var/opt/mssql/data
    ports:
      - 1433:1433
    networks:
      - lan-network

  seq-log:
    image: angelo87dock/gsweb-seq
    container_name: infra-seq
    restart: "always"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - /docker/storage/storage-seq/data:/data
    ports:
      - 5090:80
      - 5341:5341
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net